[project]
name = 'droplinked-stx-gateway'
description = ''
authors = ['Erfan Yeganegi <yeganegierfan@gmail.com']
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.droplinked-stx-gateway]
path = 'contracts/droplinked-stx-gateway.clar'
clarity_version = 2
epoch = 2.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = true
callee_filter = true
